### ISSUE TITLE
normalize_multicov.pl patch ?

### ISSUE THREAD

**Issue by lmanchon** [mtw/Bio-ViennaNGS#3]
--Hi Michael,

normalize_multicov.pl need bed12 file to run, but i have only bed3 file format, how to adapt the code
to run normalize_multicov.pl with bed3 format ?
(or maybe convert bed3 to bed12 ?)

Laurent --

**Comment by mtw** [comment]
Hi Laurent,
you can easily make a bed12 out of a bed3 for this purpose by simply adding dummy information in the 9 remaining fields and pass this file to the normalize_multicov.pl script. 
See the bed specification at https://genome.ucsc.edu/FAQ/FAQformat.html#format1 for more information on the different bed format flavours.
Cheers,
Michael

**Comment by lmanchon** [comment]
Le 12/10/2015 14:09, Michael T. Wolfinger a écrit :

> Hi Laurent,
> you can easily make a bed12 out of a bed3 for this purpose by simply 
> adding dummy information in the 9 remaining fields and pass this file 
> to the normalize_multicov.pl script.
> See the bed specification at 
> https://genome.ucsc.edu/FAQ/FAQformat.html#format1 for more 
> information on the different bed format flavours.
> Cheers,
> Michael
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mtw/Bio-ViennaNGS/issues/3#issuecomment-147377450.

Michael,

i have already done that but it failed with:

Illegal division by zero at 
/tools/perl5/modules/lib/perl5/Bio/ViennaNGS/Expression.pm line 165.

my bed12 file was formated such as:

TR25|c0_g1_i1   0       275     none    1       -       0 0 0  
1       0,      0,      0
TR25|c0_g2_i1   0       428     none    1       -       0 0 0  
1       0,      0,      0
TR26|c0_g1_i1   0       453     none    1       -       0 0 0  
1       0,      0,      0
TR27|c0_g1_i1   0       403     none    1       -       0 0 0  
1       0,      0,      0
TR27|c1_g1_i1   0       263     none    1       -       0 0 0  
1       0,      0,      2
TR28|c0_g1_i1   0       329     none    1       -       0 0 0  
1       0,      0,      0
TR29|c0_g1_i1   0       953     none    1       -       0 0 0  
1       0,      0,      0
TR29|c0_g2_i1   0       1197    none    1       -       0 0 0  
1       0,      0,      36

the last column correspond to the count.

Laurent --

---

L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
